### ISSUE TITLE
cert and key mixed up in deploy script

### ISSUE THREAD

**Issue by jkrenzer** [theohbrothers/docker-certbot-dns-cron#3]
Hi!

Looking at the code, the cert and the key are mixed up in the deployment files:

https://github.com/theohbrothers/docker-certbot-dns-cron/blob/c32e823217c775a70767e15c9ad8ec452f44830f/app/scripts/signcert-deploy-sendmail.sh#L44-L48

Thanks for having a look!

Jörn

**Comment by leojonathanoh** [comment]
@jkrenzer looks like you are right. Lets see if i can push a fix asap

**Comment by jkrenzer** [comment]
Thank you! :-)
