### ISSUE TITLE
Feature Request: Separate deploy script

### ISSUE THREAD

**Issue by jkrenzer** [theohbrothers/docker-certbot-dns-cron#4]
Hi!

As sometimes the deploy config might fail or the docker volume for the exported certs will be purged, it would be nice to have a separate script to trigger a re-deployment of the certificate and key.

Thanks!

Jörn

**Comment by leojonathanoh** [comment]
@jkrenzer does make sense, instead of using a monolithic script where the steps are not modular.

**Comment by leojonathanoh** [comment]
@jkrenzer this will be ready on the release branch on `v0.0.1`.

**Comment by jkrenzer** [comment]
Great work. Thanks!
