### ISSUE TITLE
Also deploy fullchain.pem

### ISSUE THREAD

**Issue by jkrenzer** [theohbrothers/docker-certbot-dns-cron#9]
Hi!

Sorry for bugging you again. :-)

Some services, e.g. ejabberd or prosody, need the full certificate chain to be able to serve TLS correctly.

So it would be helpfull to have the full-chain cert also available in the certs folder. Maybe as ${DOMAIN}.full.crt or the like.

Thank you for the good work and stay safe!

Jörn

**Comment by leojonathanoh** [comment]
@jkrenzer makes sense. Definitely missed out on that since `nginx` didn't need the fullchain when I initially started out creating this :P

**Comment by leojonathanoh** [comment]
@jkrenzer will be released in `v0.1.0`.

**Comment by jkrenzer** [comment]
Thanks!

**Comment by leojonathanoh** [comment]
glad to help 😃
